// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcwanryuersswulwpjqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjd2Fucnl1ZXJzc3d1bHdwanFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjA2ODMsImV4cCI6MjA2OTc5NjY4M30.Ia4DhvtpW_wVNyLzDsI5KlcuPatt_YDLKrRE4X_l1Zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});